In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from math import sqrt

In [2]:
#fazendo o download dos dados direto dos datasets presente na scikit-learn
data = datasets.load_breast_cancer()
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [3]:
#variável meta (target) -> aquilos que estamos tentando prever
#no caso: cancer benigno ou maligno
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [4]:
#linhas x colunas
data.data.shape

(569, 30)

In [5]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [8]:
#visualizando as 5 primeiras amostras
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

## TODO 1
> Separe o dataset em conjunto de treino e teste, sendo 70% para treino e 30% para teste

In [9]:
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.3, random_state=0) 

## TODO 2
> Treine um classificador SVM usando kernel linear e outro usando kernel RBF

In [10]:
clf_lin = svm.SVC(kernel='linear')
clf_lin.fit(X_train, y_train)

SVC(kernel='linear')

In [11]:
clf_rbf = svm.SVC(kernel='rbf')
clf_rbf.fit(X_train, y_train)

SVC()

## TODO 3
> Faça a predição para o conjunto de teste usando os dois kernels

In [12]:
y_pred_lin = clf_lin.predict(X_test)
y_pred_rbf = clf_rbf.predict(X_test)

In [13]:
y_pred_lin

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1])

## TODO 4
> Obtenha a Acurácia, Precision e Recall para cada kernel

In [14]:
print("Accuracy Linear Kernel:",metrics.accuracy_score(y_test, y_pred_lin))
print("Precision Linear Kernel:",metrics.precision_score(y_test, y_pred_lin))
print("Recall Linear Kernel:",metrics.recall_score(y_test, y_pred_lin))

Accuracy Linear Kernel: 0.9590643274853801
Precision Linear Kernel: 0.9809523809523809
Recall Linear Kernel: 0.9537037037037037


In [15]:
print("Accuracy RBF Kernel:",metrics.accuracy_score(y_test, y_pred_rbf))
print("Precision RBF Kernel:",metrics.precision_score(y_test, y_pred_rbf))
print("Recall RBF Kernel:",metrics.recall_score(y_test, y_pred_rbf))

Accuracy RBF Kernel: 0.9239766081871345
Precision RBF Kernel: 0.8991596638655462
Recall RBF Kernel: 0.9907407407407407


## TODO 5
> Você consegue explicar o motivos dos indicadores serem diferentes?

In [16]:
#resposta
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_lin, target_names=data.target_names))

              precision    recall  f1-score   support

   malignant       0.92      0.97      0.95        63
      benign       0.98      0.95      0.97       108

    accuracy                           0.96       171
   macro avg       0.95      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



## TODO 6

O código abaixo prepara os dados para executar uma regressao linear

In [17]:
lemonades = pd.read_csv('bases/Lemonades.csv', sep = ";")
lemonades = lemonades.drop_duplicates()
lemonades['Date'] = pd.to_datetime(lemonades['Date'])
t0 = lemonades.Date.min()
m = lemonades.Date.notnull()
lemonades.loc[m, 'Date_int'] = (lemonades.loc[m, 'Date'] - t0).dt.total_seconds()
lemonades['Date'] = np.datetime64(t0) + pd.to_timedelta(lemonades.Date_int.interpolate(), unit='s')
del lemonades['Date_int']
lemonades['Leaflets'].fillna((lemonades['Leaflets'].mean()), inplace=True)
lemonades["Sales"] = lemonades["Lemon"] + lemonades["Orange"]
lemonades["Revenue"] = lemonades["Sales"] * lemonades["Price"]
lemonades.head()

,Date,Location,Lemon,Orange,Temperature,Leaflets,Price,Sales,Revenue
0,2016-07-01,Park,97,67,70,90.0,0.25,164,41.00
1,2016-07-02,Park,98,67,72,90.0,0.25,165,41.25
2,2016-07-03,Park,110,77,71,104.0,0.25,187,46.75
3,2016-07-04,Beach,134,99,76,98.0,0.25,233,58.25
4,2016-07-05,Beach,159,118,78,135.0,0.25,277,69.25


Ajuste uma Regressão Linear aos dados para predizer vendas usando cada uma das features abaixo:

* temperature
* leaflets
* price

Calcule o RMSE

In [18]:
# temperature
X_temperature = lemonades['Temperature'].values
y_sales = lemonades['Sales'].values

lr_model_temperature = linear_model.LinearRegression()
lr_model_temperature.fit(X_temperature.reshape(-1, 1), y_sales.reshape(-1, 1))

y_temperature_pred = lr_model_temperature.predict(X_temperature.reshape(-1, 1))
rmse = sqrt(mean_squared_error(y_sales, y_temperature_pred))
print('RMSE: %.3f' % rmse)

RMSE: 41.962


In [24]:
X_temperature.reshape(-1, 1)

array([[70],
       [72],
       [71],
       [76],
       [78],
       [82],
       [81],
       [82],
       [80],
       [82],
       [83],
       [84],
       [77],
       [78],
       [75],
       [74],
       [77],
       [81],
       [78],
       [70],
       [77],
       [80],
       [81],
       [82],
       [84],
       [83],
       [80],
       [82],
       [81],
       [82],
       [82]])

In [19]:
# leaflets
X_leaflets = lemonades['Leaflets'].values

lr_model_leaflets = linear_model.LinearRegression()
lr_model_leaflets.fit(X_leaflets.reshape(-1, 1), y_sales.reshape(-1, 1))

y_leaflets_pred = lr_model_leaflets.predict(X_leaflets.reshape(-1, 1))
rmse = sqrt(mean_squared_error(y_sales, y_leaflets_pred))
print('RMSE: %.3f' % rmse)

RMSE: 25.489


In [20]:
# price
X_price = lemonades['Price'].values

lr_model_price = linear_model.LinearRegression()
lr_model_price.fit(X_price.reshape(-1, 1), y_sales.reshape(-1, 1))

y_price_pred = lr_model_price.predict(X_price.reshape(-1, 1))

rmse = sqrt(mean_squared_error(y_sales, y_price_pred))
print('RMSE: %.3f' % rmse)

RMSE: 45.368


## TODO 7
Ajuste uma Regressão Linear aos dados para predizer vendas usando as três features juntas. Calcule o RMSE

In [21]:
X = lemonades[['Temperature', 'Leaflets', 'Price']].values

lr_model = linear_model.LinearRegression()
lr_model.fit(X, y_sales.reshape(-1, 1))

y_pred = lr_model.predict(X)

rmse = sqrt(mean_squared_error(y_sales, y_pred))
print('RMSE: %.3f' % rmse)

RMSE: 17.594
